#!/bin/bash
USER=star                                    	# the user to run as
NAME="Map-Your-Night-DEV"                                  		# Name of the application
DJANGODIR=/home/$USER/Map-Your-Night-DEV             				# Django project directory
SOCKFILE=/home/$USER/Map-Your-Night-DEV/run/gunicorn.sock  		# we will communicte using this unix socket
GROUP=$USER                                     		# the group to run as
NUM_WORKERS=3                                     	# how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=starmap.settings.__init__		# which settings file should Django use
DJANGO_WSGI_MODULE=starmap.wsgi                 		# WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /home/$USER/Map-Your-Night-DEV/venv/bin/activate
export STARMAP_ENVIRONMENT=staging
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /home/$USER/Map-Your-Night-DEV/venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
