"""
Django settings for starmap project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from split_settings.tools import include
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from starmap.apps.base.utility.io import confirm_dir_exists

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FILES_DIR = os.path.join(BASE_DIR, 'files')
confirm_dir_exists(FILES_DIR)

TEMPLATES_DIR = os.path.join(FILES_DIR, 'templates')
confirm_dir_exists(TEMPLATES_DIR)

STATIC_DIR = os.path.join(FILES_DIR, 'static')
confirm_dir_exists(STATIC_DIR)

STATIC_ROOT = os.path.join(FILES_DIR, 'assets')
confirm_dir_exists(STATIC_ROOT)

MEDIA_ROOT = os.path.join(FILES_DIR, 'media')
confirm_dir_exists(MEDIA_ROOT)

FIXTURES_ROOT = os.path.join(FILES_DIR, 'fixtures')
confirm_dir_exists(FIXTURES_ROOT)

FIXTURE_DIRS = [FIXTURES_ROOT, ]

STATICFILES_DIRS = [STATIC_DIR, ]

LOG_FILE_DIR = os.path.join(FILES_DIR, 'logs')
confirm_dir_exists(LOG_FILE_DIR)

#dir for temporary files
TEMP_DIR = os.path.join(FILES_DIR, 'temp')
confirm_dir_exists(TEMP_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'uxb_ds9yv-tk@1uw&p-dc1$x0!1y(^^mb5iwys%(^uipeozdqa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #starmap apps
    'starmap.apps.base',
    'starmap.apps.site',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'starmap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'starmap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'starmap',
        'USER': 'superuser',
        'PASSWORD': 'spider@123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

ENVIRONMENT = os.environ.get('STARMAP_ENVIRONMENT', 'development')

include(
    '%s.py' % ENVIRONMENT,
    scope=globals()
)