# Generated by Django 3.0.4 on 2020-04-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='location of the product', max_length=555)),
                ('date', models.CharField(help_text='date of the product', max_length=255)),
                ('star_color', models.CharField(help_text='star color of the product', max_length=100)),
                ('frame_color', models.CharField(help_text='frame color of the product', max_length=100)),
                ('bg_color', models.CharField(help_text='Background color of the product', max_length=100)),
                ('text_color', models.CharField(help_text='text color of the product', max_length=100)),
                ('constellations', models.BooleanField(default=False)),
                ('grid', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('lat', models.CharField(help_text='Lattitude of the product', max_length=255)),
                ('lng', models.CharField(help_text='Longitude of the product', max_length=255)),
                ('font', models.CharField(help_text='text font', max_length=100)),
            ],
        ),
    ]
